[package]
name = "wolf3D"

[[dependency]]
package = "jank-stdlib"
alias = "std"

[[dependency]]
package = "jank-runtime"

[[default-include]]
package = "core"
path = "memory"

[[default-include]]
package = "core"
path = "error"

[[default-include]]
package = "core"
path = "defs"

[[default-include]]
package = "core"
path = "malloc"

[[target]]
name = "main"
type = "binary"
entry = "main.jank"
output = "main"
runtime = "jank-runtime"

