#include "jank.ebnf" ; 

inline_dereferencing = "*" , ows , identifier ;
inline_referencing = "@" , ows , identifier ;
inline_member_variable = identifier , ( "." | "->" ) , identifier ;
inline_variable = identifier ;
inline_access = "{" , ows , ( inline_referencing | inline_member_variable | inline_variable ) , ows , "}" ;

(* so we probably want one inline asm block to only access one variable *)
(* inline_asm = "asm!(\"" , { inline_access | ( alpha | digit | escape | symbol | " " ) } , "\")" ; *)
inline_asm = "asm!" , ows , "(" , ows , literal_string , ows , ")" ;
