#include "expression.ebnf" ;
#include "function.ebnf" ;

(* I loooove dylan janky *)

alpha   = "A" | "B" | "C" | "D" | "E" | "F" | "G"
        | "H" | "I" | "J" | "K" | "L" | "M" | "N"
        | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
        | "V" | "W" | "X" | "Y" | "Z" | "a" | "b"
        | "c" | "d" | "e" | "f" | "g" | "h" | "i"
        | "j" | "k" | "l" | "m" | "n" | "o" | "p"
        | "q" | "r" | "s" | "t" | "u" | "v" | "w"
        | "x" | "y" | "z" ;
digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
number = < digit > ;

(* 
structures should define whitespace within themselves. 
Whitespace outside will be defined by an enclosing structure 
the only exception is 'program', which needs to define whitespace outside of itself as it doesn't have any enclosing structure
*)
ws = " " | "\n" | "\t" | "\r" | "\f" | "\b" ;   (* whitespace *)
rws = < ws > ;                                  (* required whitespace *)
ows = { ws } ;                                  (* optional whitespace *)

type = alpha , { alpha | digit | "_" } ;
identifier = alpha , { alpha | digit | "_" } ;

(* int a = b *)
declaration = type , rws , identifier , rws , "=" , rws , expression ;

(* int foo *)
parameter = type , rws , identifier ;
parameter_list = [ parameter , { ows , "," , ows , parameter } ] ;
argument_list = [ identifier , { ows , "," , ows , identifier } ] ;

statement = declaration , ows , ";" 
          | function_call , ows , ";" 
          | "return" , rws , expression , ows , ";" ;
compound_statement = "{" , ows , { ( statement | compound_statement ) , ows } , "}" ;

program = { ows , function } , ows ;

