dylan = "jank" ;

(* it's janking time!! (yay) *)
(* holy moly, I can't wait to use these comments everywhere!!! *)    
rws = ws , { ws } ;                                   
ows = { ws } ;                                        

(* comments can contain everything except for asterisks *)
(* also, idk a better way to handle this without implementing set subtraction in the grammar *)
comment_char    = letter | digit | ws 
                | "[" | "]" | "{" | "}" | "(" | ")" | "<" | ">"         (* everything that symbol has except for the asterisk *)
                | "'" | "=" | "|" | "." | "," | ";" | "-" | "+"         (* but including double quotes and backslash *)
                | "?" | ":" | "!" | "@" | "#" | "$" | "%" | "^"
                | "&" | "*" | "/" | "~" | "`" | "\\" | "\"" ;
comment = "(*" , { comment_char } , "*)" ;
ws = " " | "\n" | "\t" | "\r" | "\f" | "\b" | comment ;   (* treat comments as whitespace *)
rws = ws , { ws } ;                                       (* required whitespace *)
ows = { ws } ;                                            (* optional whitespace *)


nesting = { { { { comment } } } } ;