[package]
name = "wordle_amongus"

[[dependency]]
package = "jank-stdlib"
alias = "std"

[[dependency]]
package = "jank-runtime"

[[default-include]]
package = "core"
path = "memory"

[[default-include]]
package = "core"
path = "error"

[[default-include]]
package = "core"
path = "defs"

[[default-include]]
package = "core"
path = "malloc"

[[target]]
name = "amongus"
type = "binary"
entry = "amongus.jank"
output = "amongus"
runtime = "jank-runtime"

