#include "value.ebnf" ;

(* 
I should have made a jank config language
making stuff yourself is the jank way 
sometimes i am lazy tho 
*)

alpha   = "A" | "B" | "C" | "D" | "E" | "F" | "G"
        | "H" | "I" | "J" | "K" | "L" | "M" | "N"
        | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
        | "V" | "W" | "X" | "Y" | "Z"
        | "a" | "b" | "c" | "d" | "e" | "f" | "g"
        | "h" | "i" | "j" | "k" | "l" | "m" | "n"
        | "o" | "p" | "q" | "r" | "s" | "t" | "u"
        | "v" | "w" | "x" | "y" | "z" ;
digit   = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;
escape  = "\\" , ( "n" | "t" | "r" | "f" | "b" | "\"" | "\\"  ) ;

(* collection of keyboard symbols excluding single and double quotes, backslash, and hash *)
symbol  = "[" | "]" | "{" | "}" | "(" | ")" | "<" | ">"                  
        | "=" | "|" | "." | "," | ";" | "-" | "+" | "_"
        | "*" | "?" | ":" | "!" | "@" | "$" | "%" 
        | "^" | "&" | "/" | "~" | "`" ;

(* comments go until a newline *)
comment = "#" , { alpha | digit | symbol | "#" | "\"" | "'" | " " | "\\" | "\t" } ;

ws = { " " | "\n" | "\t" | "\r" | comment } ;
hws = { " " | "\t" } ;                  (* horizontal whitespace *)

bare_key    = < alpha | digit | "_" | "-" > ;
quoted_key  = "\"" , { alpha | digit | symbol | "'" | " " | "#" } , "\"" 
            | "'" , { alpha | digit | symbol | "\"" | " " | "#" } , "'" ;
key = ( quoted_key | bare_key ) , { hws , "." , hws , ( quoted_key | bare_key ) } ;

table   = "[" , hws , key , hws , "]" 
        | "[[" , hws , key , hws , "]]" ;
key_value = key , hws , "=" , hws , value ;
statement = key_value | table ;

toml = { ws , statement } , ws ;
